### ISSUE TITLE
Getting error while run make command

### ISSUE THREAD

**Issue by AtiqulHaque** [lucianoayres/nino-cli#1]
Running tests...
go test -C src ./...
go: cannot find main module, but found .git/config in /Golang/AI/nino
        to create a module there, run:
        go mod init
make: *** [test] Error 1

**Comment by lucianoayres** [comment]
Thanks for the report @AtiqulHaque I’ve updated the installation process and made the binary available for download. Please [follow these instructions](https://github.com/lucianoayres/nino-cli#method-1-download-the-binary-from-github-releases) and let me know how it works for you.
