### ISSUE TITLE
Does the -prompt-file option support multiple files?

### ISSUE THREAD

**Issue by lnxyz** [lucianoayres/nino-cli#2]
Does the -prompt-file option allow specifying multiple files at once?

**Comment by lucianoayres** [comment]
The `-prompt-file` argument currently supports a single text file, but you can pass the contents of multiple files and achieve the same result using command substitution in Bash:

`nino $(cat prompt_file_1.txt prompt_file_2.txt)`

Keep in mind that the the `cat` command merges the contents of both files and passes them as a single argument to `nino`. If you need to process multiple prompt files individually, you can use command chaining:

`nino -prompt-file prompt_file_1.txt; nino -prompt_file_2.txt`

Alternatively, you can run it conditionally, where the second command will only run if the first runs successfully:

`nino -prompt-file prompt_file_1.txt && nino -prompt_file_2.txt`

**Comment by lnxyz** [comment]
Thanks for the explanation, @lucianoayres ! Using command substitution or chaining allows me to process multiple prompt files effectively. This issue is now resolved.
